"""Depth-aware ETF signals; proposed legs are not atomic or guaranteed profits."""
from __future__ import annotations

import math
from typing import Any, Iterable, Mapping

WEIGHTS = {"BULL": 1, "BEAR": 1, "RITC": 2}
EQUITY_FEE = 0.02
DEFAULT_ENTRY_BUFFER_CAD = 0.10
CONVERTER_BLOCK = 10_000
CONVERTER_COST_USD = 1_500
TENDER_MIN_ADVERSE_MOVE_USD_PER_SHARE = 0.05


def exposure(positions: Mapping[str, float]) -> dict[str, float]:
    """Calculate weighted ETF gross and net exposure."""
    values = [positions.get(t, 0) * w for t, w in WEIGHTS.items()]
    return {"gross": sum(abs(v) for v in values), "net": sum(values)}


def within_limits(positions: Mapping[str, float], legs: Iterable[tuple[str, float]], gross_limit: float,
                  net_limit: float) -> bool:
    """Check current exposure and every sequential fill, including ETF weight."""
    p = dict(positions)
    for leg in [None, *legs]:
        if leg:
            ticker, quantity = leg
            p[ticker] = p.get(ticker, 0) + quantity
        risk = exposure(p)
        if risk["gross"] > gross_limit or abs(risk["net"]) > net_limit:
            return False
    return True


def vwap(book: Mapping[str, Any], action: str, quantity: int) -> float:
    """Calculate executable depth-weighted price for one order direction."""
    if quantity <= 0:
        raise ValueError("quantity must be positive")
    side = "asks" if action == "BUY" else "bids"
    levels = sorted(book[side], key=lambda row: row["price"], reverse=side == "bids")
    remaining, total = quantity, 0.0
    for row in levels:
        available = max(0, row["quantity"] - row.get("quantity_filled", 0))
        take = min(remaining, available)
        total += take * row["price"]
        remaining -= take
        if remaining == 0:
            return total / quantity
    raise ValueError("insufficient visible depth")


def _best_price(book: Mapping[str, Any], action: str) -> float:
    return vwap(book, action, 1)


def fx_reference_rate(snapshot: Mapping[str, Any]) -> float:
    """Midpoint reference used only to compare CAD and USD basket economics.

    Basket execution does not trade gross USD.  The strategy holds the natural
    RITC/USD financing leg and converts only the final net USD result, so entry
    ranking must not charge a fictitious gross FX spread.
    """
    book = snapshot["books"]["USD"]
    return (_best_price(book, "SELL") + _best_price(book, "BUY")) / 2


def trade_cashflow(ticker: str, quantity: int, price: float) -> dict[str, float]:
    """Return signed cash generated by one filled equity order, after commission.

    Positive ``quantity`` is a buy. BULL/BEAR settle in CAD and RITC settles in
    USD. The USD security itself is handled by :func:`net_usd_value_cad` and is
    not an equity leg.
    """
    if ticker not in WEIGHTS:
        raise ValueError(f"unsupported ETF equity cashflow ticker: {ticker}")
    cash = -quantity * price - abs(quantity) * EQUITY_FEE
    return {"CAD": cash if ticker in {"BULL", "BEAR"} else 0.0,
            "USD": cash if ticker == "RITC" else 0.0}


def executable_trade_cashflow(snapshot: Mapping[str, Any], ticker: str, quantity: int) -> dict[str, Any]:
    """Price one signed equity order and return its currency cashflow."""
    if quantity == 0:
        raise ValueError("quantity must be nonzero")
    action = "BUY" if quantity > 0 else "SELL"
    price = vwap(snapshot["books"][ticker], action, abs(quantity))
    return {"ticker": ticker, "quantity": quantity, "price": price,
            "cashflow": trade_cashflow(ticker, quantity, price)}


def cashflow_totals(rows: Iterable[Mapping[str, Any]]) -> dict[str, float]:
    total = {"CAD": 0.0, "USD": 0.0}
    for row in rows:
        cashflow = row.get("cashflow", row)
        total["CAD"] += float(cashflow.get("CAD", 0.0))
        total["USD"] += float(cashflow.get("USD", 0.0))
    return total


def net_usd_value_cad(snapshot: Mapping[str, Any], net_usd: float) -> dict[str, Any]:
    """Value one final net USD balance at executable FX, without a gross round trip."""
    if abs(net_usd) < 1e-9:
        return {"net_usd": net_usd, "action": "NONE", "quantity": 0,
                "fx_price": None, "cad_value": 0.0}
    action = "SELL" if net_usd > 0 else "BUY"
    quantity = max(1, math.ceil(abs(net_usd) - 1e-9))
    price = vwap(snapshot["books"]["USD"], action, quantity)
    return {"net_usd": net_usd, "action": action, "quantity": quantity,
            "fx_price": price, "cad_value": net_usd * price}


def liquidation_value(snapshot: Mapping[str, Any], positions: Mapping[str, float]) -> dict[str, Any]:
    """Value flattening an ETF account by equities first and final net USD last."""
    fills: list[dict[str, Any]] = []
    for ticker in ("BULL", "BEAR", "RITC"):
        position = positions.get(ticker, 0)
        if not position:
            continue
        if int(position) != position:
            raise ValueError(f"fractional equity position for {ticker}")
        fills.append(executable_trade_cashflow(snapshot, ticker, -int(position)))
    cash = cashflow_totals(fills)
    cash["USD"] += float(positions.get("USD", 0.0))
    fx = net_usd_value_cad(snapshot, cash["USD"])
    return {"fills": fills, "cashflow_cad_before_fx": cash["CAD"],
            "net_usd_before_fx": cash["USD"], "fx": fx,
            "total_cad": cash["CAD"] + fx["cad_value"]}


def basket_opportunity(snapshot: Mapping[str, Any], direction: int, quantity: int,
                       gross_limit: float | None = None, net_limit: float | None = None,
                       entry_buffer_cad: float = DEFAULT_ENTRY_BUFFER_CAD) -> dict[str, Any]:
    """Price one fully hedged ETF basket using executable equity depth.

    ``direction=1`` sells BULL/BEAR and buys RITC; ``direction=-1`` does the
    inverse.  Gross USD funding is *not* traded by the strategy. RITC is marked
    to an FX midpoint for entry ranking and only the eventual net USD P&L is
    converted at executable FX when the basket closes.
    """
    if direction not in (-1, 1):
        raise ValueError("direction must be -1 or 1")
    if not 0 < quantity <= 10000:
        raise ValueError("ETF child quantity must be 1..10000")
    if entry_buffer_cad < 0:
        raise ValueError("entry buffer cannot be negative")
    books = snapshot["books"]
    positions = {s["ticker"]: s["position"] for s in snapshot["securities"]}
    stock_action = "SELL" if direction == 1 else "BUY"
    etf_action = "BUY" if direction == 1 else "SELL"
    basket_prices = {ticker: vwap(books[ticker], stock_action, quantity) for ticker in ("BULL", "BEAR")}
    etf_price = vwap(books["RITC"], etf_action, quantity)
    fx_reference = fx_reference_rate(snapshot)
    basket_cad = sum(basket_prices.values())
    etf_cad = etf_price * fx_reference
    fees_cad = 2 * EQUITY_FEE + EQUITY_FEE * fx_reference
    edge = direction * (basket_cad - etf_cad) - fees_cad
    legs = [("BULL", -direction * quantity), ("BEAR", -direction * quantity), ("RITC", direction * quantity)]
    allowed = None if gross_limit is None or net_limit is None else within_limits(positions, legs, gross_limit, net_limit)
    return {
        "direction": "LONG_RITC_SHORT_BASKET" if direction == 1 else "SHORT_RITC_LONG_BASKET",
        "legs": legs,
        "fx_leg": None,
        "fx_treatment": "No gross FX trade; RITC is marked at midpoint and final net USD is converted on exit.",
        "executable_prices": {"BULL": basket_prices["BULL"], "BEAR": basket_prices["BEAR"],
                              "RITC_usd": etf_price, "USD_reference_cad_per_usd": fx_reference},
        "basket_cad_per_unit": basket_cad,
        "ritc_cad_per_unit": etf_cad,
        "fees_cad_per_unit": fees_cad,
        "edge_cad_per_unit": edge,
        "entry_buffer_cad_per_unit": entry_buffer_cad,
        "eligible_after_buffer": edge >= entry_buffer_cad,
        "within_configured_limits": allowed,
    }


def basket_entry_value_cad(snapshot: Mapping[str, Any], fills: Iterable[Mapping[str, Any]]) -> float:
    """Mark completed basket entry cashflows to the non-executed FX reference."""
    cash = cashflow_totals(fills)
    return cash["CAD"] + cash["USD"] * fx_reference_rate(snapshot)


def basket_close_now(snapshot: Mapping[str, Any], held: Mapping[str, Any]) -> dict[str, Any]:
    """Calculate executable P&L from reversing a stored basket entry now.

    Entry cashflows are immutable historical fills. Exit equity legs are priced
    at current visible depth and only the combined entry/exit net USD balance is
    converted through the current FX book.
    """
    entry_fills = list(held["entry_fills"])
    exit_fills = [executable_trade_cashflow(snapshot, row["ticker"], -int(row["quantity"]))
                  for row in entry_fills]
    cash = cashflow_totals([*entry_fills, *exit_fills])
    fx = net_usd_value_cad(snapshot, cash["USD"])
    return {"entry_fills": entry_fills, "exit_fills": exit_fills,
            "cashflow_cad_before_fx": cash["CAD"], "net_usd_before_fx": cash["USD"],
            "fx": fx, "pnl_cad": cash["CAD"] + fx["cad_value"]}


def serial_basket_choice(snapshot: Mapping[str, Any], filled: Iterable[Mapping[str, Any]],
                         remaining_legs: Iterable[tuple[str, int]]) -> dict[str, Any]:
    """Compare finishing a serial basket with reversing already-filled legs.

    Finishing is valued by combining immutable fill cashflows with current
    executable prices for the remaining entry legs, marked at the non-executed
    FX reference. Aborting is valued as executable close-now P&L on only the
    filled legs, including final net-USD conversion.
    """
    filled_rows = list(filled)
    remaining_rows = [executable_trade_cashflow(snapshot, ticker, int(quantity))
                      for ticker, quantity in remaining_legs]
    finish_value = basket_entry_value_cad(snapshot, [*filled_rows, *remaining_rows])
    abort_exits = [executable_trade_cashflow(snapshot, row["ticker"], -int(row["quantity"]))
                   for row in reversed(filled_rows)]
    abort_cash = cashflow_totals([*filled_rows, *abort_exits])
    abort_fx = net_usd_value_cad(snapshot, abort_cash["USD"])
    abort_pnl = abort_cash["CAD"] + abort_fx["cad_value"]
    return {"finish_value_cad": finish_value, "abort_pnl_cad": abort_pnl,
            "finish": finish_value >= 0 and finish_value >= abort_pnl,
            "projected_remaining_fills": remaining_rows,
            "abort_exit_fills": abort_exits, "abort_fx": abort_fx}


def _tender_liquidation_reserve(snapshot: Mapping[str, Any], action: str, quantity: int,
                                edge_usd: float) -> dict[str, float]:
    """Stress a tender unwind for depth, serial-child drift, and one extra FX spread.

    The old fixed C$0.0025/share threshold was negligible relative to one tick.
    This reserve scales with tender size, observed depth slippage, quoted spread,
    and the number of legal RITC child orders. It is intentionally conservative.
    """
    unwind = "SELL" if action == "BUY" else "BUY"
    book = snapshot["books"]["RITC"]
    best = _best_price(book, unwind)
    full = vwap(book, unwind, quantity)
    spread = max(0.0, _best_price(book, "BUY") - _best_price(book, "SELL"))
    depth_slippage = abs(full - best)
    securities = {row["ticker"]: row for row in snapshot["securities"]}
    child_cap = max(1, min(10_000, int(securities["RITC"].get("max_trade_size", 10_000))))
    children = math.ceil(quantity / child_cap)
    adverse_per_share = (max(TENDER_MIN_ADVERSE_MOVE_USD_PER_SHARE, 2 * spread)
                         + depth_slippage + 0.5 * spread * max(0, children - 1))
    reserve_usd = quantity * adverse_per_share
    fx_book = snapshot["books"]["USD"]
    fx_bid = _best_price(fx_book, "SELL")
    fx_ask = _best_price(fx_book, "BUY")
    fx_spread = max(0.0, fx_ask - fx_bid)
    fx_rate = fx_ask
    reserve_cad = reserve_usd * fx_rate + abs(edge_usd) * fx_spread
    return {"reserve_cad": reserve_cad, "reserve_usd": reserve_usd,
            "adverse_usd_per_share": adverse_per_share,
            "observed_depth_slippage_usd_per_share": depth_slippage,
            "ritc_spread_usd": spread, "child_orders": children,
            "fx_spread_cad_per_usd": fx_spread}


def tender_opportunity(snapshot: Mapping[str, Any], offer: Mapping[str, Any]) -> dict[str, Any]:
    """Price a fixed RITC tender through liquidation and final net USD conversion."""
    report = {"tender_id": offer["tender_id"], "decision": "REVIEW"}
    try:
        if offer["ticker"] != "RITC" or not offer["is_fixed_bid"]:
            raise ValueError("only fixed-price RITC tenders supported")
        action, quantity = offer["action"], offer["quantity"]
        if action not in ("BUY", "SELL"):
            raise ValueError("unknown tender action")
        if not isinstance(quantity, (int, float)) or quantity <= 0 or int(quantity) != quantity:
            raise ValueError("tender quantity must be a positive integer")
        quantity = int(quantity)
        unwind = "SELL" if action == "BUY" else "BUY"
        market = vwap(snapshot["books"]["RITC"], unwind, quantity)
        edge_usd = ((market - offer["price"]) * (1 if action == "BUY" else -1) - EQUITY_FEE) * quantity
        starting_usd = next((float(row["position"]) for row in snapshot["securities"] if row["ticker"] == "USD"), 0.0)
        resulting_usd = starting_usd + edge_usd
        starting_fx = net_usd_value_cad(snapshot, starting_usd)
        resulting_fx = net_usd_value_cad(snapshot, resulting_usd)
        edge_cad = resulting_fx["cad_value"] - starting_fx["cad_value"]
        reserve = _tender_liquidation_reserve(snapshot, action, quantity, edge_usd)
        report.update(estimated_unwind_profit_usd=edge_usd,
                      estimated_unwind_profit_cad=edge_cad,
                      starting_usd_balance=starting_usd,
                      resulting_net_usd_balance=resulting_usd,
                      net_fx_action=resulting_fx["action"], net_fx_price=resulting_fx["fx_price"],
                      liquidation_reserve_cad=reserve["reserve_cad"],
                      liquidation_reserve=reserve,
                      note="Full-depth estimate; final net USD is converted only after liquidation.")
    except (ValueError, KeyError) as error:
        report["skip"] = str(error)
    return report


def _converter_route(snapshot: Mapping[str, Any], positions: Mapping[str, float], converter: str,
                     blocks: int) -> dict[str, Any]:
    projected = {ticker: float(positions.get(ticker, 0.0)) for ticker in (*WEIGHTS, "USD")}
    units = blocks * CONVERTER_BLOCK
    if converter == "ETF-Redemption":
        projected["RITC"] -= units
        projected["BULL"] += units
        projected["BEAR"] += units
    elif converter == "ETF-Creation":
        projected["BULL"] -= units
        projected["BEAR"] -= units
        projected["RITC"] += units
    else:
        raise ValueError("unknown converter")
    projected["USD"] -= blocks * CONVERTER_COST_USD
    liquidation = liquidation_value(snapshot, projected)
    return {"blocks": blocks, "projected_positions": projected, "liquidation": liquidation,
            "total_cad": liquidation["total_cad"]}


def manual_converter_opportunities(snapshot: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Optimize eligible manual converter use against full direct liquidation.

    Every candidate block count is revalued from the resulting portfolio. This
    captures the existing USD cash balance (including tender cash), converter
    fees in USD, possible FX-direction changes, and non-linear depth across
    multiple 10,000-unit blocks.
    """
    positions = {row["ticker"]: float(row["position"]) for row in snapshot["securities"]}
    results: list[dict[str, Any]] = []
    try:
        direct = liquidation_value(snapshot, positions)
    except (ValueError, KeyError):
        return results

    candidates = {
        "ETF-Redemption": max(0, int(positions.get("RITC", 0)) // CONVERTER_BLOCK),
        "ETF-Creation": min(max(0, int(-positions.get("RITC", 0)) // CONVERTER_BLOCK),
                            max(0, int(positions.get("BULL", 0)) // CONVERTER_BLOCK),
                            max(0, int(positions.get("BEAR", 0)) // CONVERTER_BLOCK)),
    }
    for converter, available_blocks in candidates.items():
        if not available_blocks:
            continue
        routes: list[dict[str, Any]] = []
        for blocks in range(1, available_blocks + 1):
            try:
                route = _converter_route(snapshot, positions, converter, blocks)
            except (ValueError, KeyError):
                continue
            route["advantage_cad"] = route["total_cad"] - direct["total_cad"]
            routes.append(route)
        if not routes:
            continue
        best = max(routes, key=lambda row: row["advantage_cad"])
        blocks = int(best["blocks"])
        advantage = float(best["advantage_cad"])
        redemption = converter == "ETF-Redemption"
        results.append({
            "converter": converter,
            "manual_action": "UNWIND" if redemption else "WIND",
            "blocks": blocks,
            "available_blocks": available_blocks,
            "block_size": CONVERTER_BLOCK,
            "convert_from": {"RITC": CONVERTER_BLOCK} if redemption
                            else {"BULL": CONVERTER_BLOCK, "BEAR": CONVERTER_BLOCK},
            "convert_to": {"BULL": CONVERTER_BLOCK, "BEAR": CONVERTER_BLOCK} if redemption
                          else {"RITC": CONVERTER_BLOCK},
            "direct_liquidation_value_cad": direct["total_cad"],
            "converter_route_value_cad": best["total_cad"],
            "resulting_net_usd_before_fx": best["liquidation"]["net_usd_before_fx"],
            # Preserve the historical field's per-block meaning for the CLI
            # while exposing the optimized route's total advantage explicitly.
            "estimated_advantage_cad": advantage / blocks,
            "estimated_total_advantage_cad": advantage,
            "estimated_advantage_cad_per_block": advantage / blocks,
            "evaluated_block_counts": [row["blocks"] for row in routes],
            "recommended": advantage > 0,
            "reason": ("optimized manual conversion beats direct liquidation" if advantage > 0
                       else "direct liquidation is cheaper than every eligible converter size"),
        })
    return results


def analyze(snapshot: Mapping[str, Any], quantity: int = 1000, gross_limit: float | None = None,
            net_limit: float | None = None) -> dict[str, Any]:
    """Evaluate ETF basket, tender, and manual-converter opportunities without trading."""
    if not 0 < quantity <= 10000:
        raise ValueError("ETF child quantity must be 1..10000")
    positions = {s["ticker"]: s["position"] for s in snapshot["securities"]}
    results = []
    for direction in (1, -1):
        try:
            results.append(basket_opportunity(snapshot, direction, quantity, gross_limit, net_limit))
        except ValueError as error:
            results.append({"direction": direction, "skip": str(error)})
    tenders = [tender_opportunity(snapshot, offer) for offer in snapshot.get("tenders", [])]
    converters = manual_converter_opportunities(snapshot)
    return {"exposure": exposure(positions), "opportunities": results,
            "tenders": tenders, "manual_converters": converters}
